/**
 * Leads: one row per enquiry.
 *
 * This is the table the business exists to fill. Everything else - the taxonomy,
 * the customers, the charts still to come - is here to make these rows precise
 * enough to answer one question: *what should we put in the next 5kg?*
 *
 * WHAT IS REQUIRED, AND WHY SO LITTLE
 * Only the customer, when they made contact, which platform, and what stage the
 * enquiry is at. Everything describing the garment is nullable, because a real
 * first message is "do you have batik frocks?" - no size, no fabric, no quantity.
 * Requiring those fields would mean either turning away the enquiry or inventing
 * data, and invented data is worse than absent data when the whole point is to
 * measure demand honestly.
 *
 * WHAT IS *NOT* HERE
 * "Requests by Customer", "Customer Type", "Sub-Cat Demand" and "Days Since
 * Contact" were all on the business's list of lead columns. None of them is a fact
 * about this enquiry: they are counts over other rows, or arithmetic on today's
 * date. They are computed on read - see `customer_summary` and @/lib/time - so
 * they cannot go stale.
 *
 * ONE DENORMALISED COLUMN
 * `categoryId` duplicates what the sub-category already knows. It is here so the
 * database itself can refuse a lead whose sub-category sits under a different
 * category, via the composite foreign key below. Without it, "Footwear / Batik
 * Frock" is one careless form post away, and it would poison every chart that
 * groups demand by category.
 */
import { relations, sql } from 'drizzle-orm';
import {
  check,
  foreignKey,
  index,
  integer,
  pgTable,
  primaryKey,
  text,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

import { appUser } from './auth';
import { customers } from './customers';
import {
  categories,
  clothGenders,
  fabrics,
  leadStatuses,
  platforms,
  sizes,
  subcategories,
  tags,
  urgencyLevels,
} from './taxonomy';

import { instant, primaryId, softDelete, timestamps } from './columns';

/**
 * How the row got into the database.
 *
 * Worth recording because the three routes have different trustworthiness. A lead
 * typed by staff was read by a human; one from a CSV import was transcribed in
 * bulk; one from an n8n automation was parsed from a social media message and may
 * need review. When a figure looks wrong, this is the first column to check.
 */
export const leadSources = ['manual', 'import', 'automation'] as const;
export type LeadSource = (typeof leadSources)[number];

export const leads = pgTable(
  'leads',
  {
    id: primaryId(),

    /**
     * Sequential, human-quotable reference. "Lead 148" in a WhatsApp message to a
     * colleague; the UUID is unusable for that. Generated by the database, so two
     * simultaneous inserts cannot collide on it.
     */
    reference: integer('reference').notNull().generatedAlwaysAsIdentity({ startWith: 1 }),

    customerId: uuid('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'restrict' }),

    /**
     * When the customer made contact - the "Date" column.
     *
     * Distinct from `createdAt`, which is when the row was typed. Entering
     * yesterday's WhatsApp messages this morning must not make them look like
     * today's demand, and "days since contact" has to count from the conversation,
     * not from the data entry.
     */
    contactedAt: instant('contacted_at')
      .notNull()
      .default(sql`now()`),

    /* ---- where it came from -------------------------------------------- */

    platformId: uuid('platform_id')
      .notNull()
      .references(() => platforms.id, { onDelete: 'restrict' }),

    /* ---- what they asked for ------------------------------------------- */

    categoryId: uuid('category_id').references(() => categories.id, { onDelete: 'restrict' }),
    subcategoryId: uuid('subcategory_id').references(() => subcategories.id, {
      onDelete: 'restrict',
    }),
    clothGenderId: uuid('cloth_gender_id').references(() => clothGenders.id, {
      onDelete: 'restrict',
    }),
    fabricId: uuid('fabric_id').references(() => fabrics.id, { onDelete: 'restrict' }),
    sizeId: uuid('size_id').references(() => sizes.id, { onDelete: 'restrict' }),

    /** Pieces wanted. Null means they did not say, which is not the same as zero. */
    quantity: integer('quantity'),

    /**
     * Anything the taxonomy has no word for: "the green one in your third photo",
     * "same as her sister's". Often the most useful column on the row, and the one
     * that tells you which taxonomy value is missing.
     */
    request: text('request'),

    /* ---- how it is going ----------------------------------------------- */

    urgencyId: uuid('urgency_id').references(() => urgencyLevels.id, { onDelete: 'restrict' }),

    statusId: uuid('status_id')
      .notNull()
      .references(() => leadStatuses.id, { onDelete: 'restrict' }),

    /**
     * When the status last changed. Answers "how long has this been sitting in
     * Sourcing?", which is a different and more actionable question than how long
     * ago the customer wrote.
     */
    statusChangedAt: instant('status_changed_at')
      .notNull()
      .default(sql`now()`),

    /** Internal working notes on this enquiry. Never shown to the customer. */
    notes: text('notes'),

    /* ---- provenance ---------------------------------------------------- */

    source: text('source', { enum: leadSources as unknown as [LeadSource, ...LeadSource[]] })
      .notNull()
      .default('manual'),

    /**
     * Who entered it. Null for automation, and for a staff account later removed -
     * `set null` rather than `restrict`, because a departed colleague must not make
     * their leads undeletable.
     */
    createdById: uuid('created_by_id').references(() => appUser.id, { onDelete: 'set null' }),

    ...timestamps,
    ...softDelete,
  },
  (table) => [
    /**
     * The sub-category must belong to the category. Enforced by the database, not
     * by the form, because a Server Action is only one of several ways rows arrive.
     *
     * Depends on the unique index on `subcategories (id, category_id)` created in
     * the same migration.
     */
    foreignKey({
      name: 'leads_subcategory_in_category_fk',
      columns: [table.subcategoryId, table.categoryId],
      foreignColumns: [subcategories.id, subcategories.categoryId],
    }).onDelete('restrict'),

    /**
     * A composite foreign key is not checked when any of its columns is null, so
     * without this a sub-category could be stored with no category at all and skip
     * the check above.
     */
    check(
      'leads_subcategory_needs_category',
      sql`${table.subcategoryId} is null or ${table.categoryId} is not null`
    ),

    check('leads_quantity_positive', sql`${table.quantity} is null or ${table.quantity} > 0`),

    check(
      'leads_source_valid',
      sql.raw(`"source" in (${leadSources.map((source) => `'${source}'`).join(', ')})`)
    ),

    /** Quotable reference, and the lookup behind /leads/148. */
    uniqueIndex('leads_reference_key').on(table.reference),

    /**
     * The customer's history, newest first. Also what makes the repeat-customer
     * counts in `customer_summary` cheap.
     */
    index('leads_customer_idx').on(table.customerId, table.contactedAt.desc()),

    /** The default listing: newest enquiries first. */
    index('leads_contacted_idx').on(table.contactedAt.desc()),

    /** The work queue: everything at a given stage, oldest first. */
    index('leads_status_idx').on(table.statusId, table.contactedAt.desc()),

    /** The demand questions: what is being asked for, and through which channel. */
    index('leads_subcategory_idx').on(table.subcategoryId),
    index('leads_category_idx').on(table.categoryId),
    index('leads_fabric_idx').on(table.fabricId),
    index('leads_platform_idx').on(table.platformId),
  ]
);

/**
 * Tags on a lead: many to many.
 *
 * A junction table rather than a `text[]` column or JSON, because the tags are
 * rows in a taxonomy the business edits. Renaming "Hand-Drawn Batik" has to update
 * every lead that carries it, and that only comes free if the leads reference it by
 * id. Counting demand per tag then costs one group-by instead of unnesting arrays.
 */
export const leadTags = pgTable(
  'lead_tags',
  {
    leadId: uuid('lead_id')
      .notNull()
      .references(() => leads.id, { onDelete: 'cascade' }),
    tagId: uuid('tag_id')
      .notNull()
      .references(() => tags.id, { onDelete: 'restrict' }),
  },
  (table) => [
    /** The pair is the key: a tag cannot be on the same lead twice. */
    primaryKey({ columns: [table.leadId, table.tagId] }),
    /** "Which leads carry this tag" - the direction the primary key cannot serve. */
    index('lead_tags_tag_idx').on(table.tagId),
  ]
);

export const leadRelations = relations(leads, ({ one, many }) => ({
  customer: one(customers, { fields: [leads.customerId], references: [customers.id] }),
  platform: one(platforms, { fields: [leads.platformId], references: [platforms.id] }),
  category: one(categories, { fields: [leads.categoryId], references: [categories.id] }),
  subcategory: one(subcategories, {
    fields: [leads.subcategoryId],
    references: [subcategories.id],
  }),
  clothGender: one(clothGenders, { fields: [leads.clothGenderId], references: [clothGenders.id] }),
  fabric: one(fabrics, { fields: [leads.fabricId], references: [fabrics.id] }),
  size: one(sizes, { fields: [leads.sizeId], references: [sizes.id] }),
  urgency: one(urgencyLevels, { fields: [leads.urgencyId], references: [urgencyLevels.id] }),
  status: one(leadStatuses, { fields: [leads.statusId], references: [leadStatuses.id] }),
  createdBy: one(appUser, { fields: [leads.createdById], references: [appUser.id] }),
  tags: many(leadTags),
}));

export const leadTagRelations = relations(leadTags, ({ one }) => ({
  lead: one(leads, { fields: [leadTags.leadId], references: [leads.id] }),
  tag: one(tags, { fields: [leadTags.tagId], references: [tags.id] }),
}));

export type Lead = typeof leads.$inferSelect;
export type NewLead = typeof leads.$inferInsert;
